name: Secrets & Vars Workflow

on:
  workflow_dispatch:

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      # Repository level secrets
      DUMMY_USERNAME: ${{ secrets.DUMMY_USERNAME }}
      DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}

      # Repository level vars
      DUMMY_STATUS: ${{ vars.DUMMY_STATUS }}

      # Env level secrets
      DEV_HOST: ${{ secrets.DEV_HOST }}

      # Env level vars
      DEV_STATUS: ${{ vars.DEV_STATUS }}
    steps:
      - name: Inspect repository secrets & vars
        run: |
          echo "DUMMY_USERNAME: $DUMMY_USERNAME"
          echo "DUMMY_PASSWORD: $DUMMY_PASSWORD"
          echo "DUMMY_STATUS: $DUMMY_STATUS"

      - name: Inspect env secrets & vars
        run: |
          echo "DEV_HOST: $DEV_HOST"
          echo "DEV_STATUS: $DEV_STATUS"

  prod-job:
    runs-on: ubuntu-latest
    environment: prod
    env:
      # Repository level secrets
      DUMMY_USERNAME: ${{ secrets.DUMMY_USERNAME }}
      DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}

      # Repository level vars
      DUMMY_STATUS: ${{ vars.DUMMY_STATUS }}

      # Env level secrets
      PROD_HOST: ${{ secrets.PROD_HOST }}

      # Env level vars
      PROD_STATUS: ${{ vars.PROD_STATUS }}
    steps:
      - name: Inspect repository secrets & vars
        run: |
          echo "DUMMY_USERNAME: $DUMMY_USERNAME"
          echo "DUMMY_PASSWORD: $DUMMY_PASSWORD"
          echo "DUMMY_STATUS: $DUMMY_STATUS"

      - name: Inspect env secrets & vars
        run: |
          echo "DEV_HOST: $DEV_HOST"
          echo "DEV_STATUS: $DEV_STATUS"